### ISSUE TITLE
improving video quality settings

### ISSUE THREAD

**Issue by DonCanjas** [andiandi13/mpv-config-for-MPC-users#1]
mpv by default will have some filtering applied to, like debanding, and will scale video with bilinear (which is very poor quality, in case you're not aware). I recommed adding these settings, which I find to get decent quality:

```
#Decode Opts
vo=gpu
profile=gpu-hq
hwdec-codecs=all
hwdec=d3d11va # windows only

#hwdec=auto-safe #Linux, unless you know what you're doing
#hwdec=videotoolbox #mac only


#Scaling algorithm for profile=gpu-hq
scale=spline36
dscale=spline36
cscale=spline36


#Filters
interpolation=no
deinterlace=no
dither-depth=auto
deband=no 
```

**Comment by andiandi13** [comment]
@DonCanjas Thank you, I'm always willing to improve the file as long as there are no downsides.
